SELECT COMT
FROM gcp-prod-edp-lake.DLKL2EF22.L2EF_FMIL_SGMT_IDVL_INFO_MMLY_H A 
LEFT JOIN gcp-prod-edp-lake. DLKC1CO_L1COM_ENTR_NO_KEY_REL_CZ M 
	ON A ENTR_NO = M.ENTR_NO 
LEFT JOIN gcp-prod-edp-lake DLKC1CO_LICOM_CUST_NO_KEY_REL_CZ N 
	ON A CUST_NO=N.CUST_NO 
WHERE 1 = 1
-- Add to 257_L2EF_FMIL_SGMT_IDVL_INFO_MMLY_H 아웃바운드[(T_0630), by 진태만]
;
